"""Small character map for normalizing crisis rule input only.

This intentionally covers the vocabulary of ``safety.py`` and its regression
corpus, rather than attempting general-purpose Chinese translation. The caller
keeps the original message for storage, model input, and display.
"""

# Keep variants grouped by the simplified character used in the crisis rules.
# Some characters (for example 著 and 睏) are alternate written forms rather
# than general traditional-to-simplified conversions.
SIMPLIFIED_TO_TRADITIONAL_VARIANTS: dict[str, str] = {
    "了": "瞭",
    "业": "業",
    "个": "個",
    "么": "麼麽",
    "你": "妳",
    "优": "優",
    "义": "義",
    "书": "書",
    "买": "買",
    "价": "價",
    "会": "會",
    "经": "經",
    "伤": "傷",
    "伞": "傘",
    "它": "牠",
    "吃": "喫",
    "吊": "弔",
    "写": "寫",
    "准": "準",
    "划": "劃",
    "别": "別",
    "劝": "勸",
    "励": "勵",
    "务": "務",
    "劲": "勁",
    "卖": "賣",
    "只": "隻",
    "吓": "嚇",
    "困": "睏",
    "备": "備",
    "图": "圖",
    "妈": "媽",
    "学": "學",
    "实": "實実",
    "对": "對対",
    "帮": "幫",
    "干": "幹",
    "并": "並併",
    "恋": "戀",
    "户": "戶",
    "报": "報",
    "据": "據",
    "搜": "蒐",
    "声": "聲",
    "处": "處",
    "撑": "撐",
    "攒": "攢",
    "才": "纔",
    "数": "數",
    "断": "斷",
    "无": "無",
    "寻": "尋",
    "应": "應",
    "当": "當",
    "机": "機",
    "杀": "殺",
    "样": "樣",
    "桥": "橋",
    "楼": "樓",
    "残": "殘",
    "气": "氣気",
    "没": "沒",
    "热": "熱",
    "温": "溫",
    "环": "環",
    "现": "現",
    "点": "點",
    "着": "著",
    "真": "眞",
    "种": "種",
    "绳": "繩縄",
    "结": "結",
    "绝": "絕絶",
    "药": "藥葯薬",
    "营": "營",
    "虑": "慮",
    "计": "計",
    "记": "記",
    "论": "論",
    "认": "認",
    "评": "評",
    "询": "詢",
    "语": "語",
    "诺": "諾",
    "请": "請",
    "这": "這",
    "遗": "遺",
    "让": "讓譲",
    "远": "遠",
    "里": "裡裏",
    "销": "銷",
    "问": "問",
    "闻": "聞",
    "队": "隊",
    "预": "預",
    "项": "項",
    "顶": "頂",
    "题": "題",
    "饿": "餓",
    "轻": "輕軽",
    "说": "說",
    "简": "簡",
    "系": "係繫",
    "紧": "緊",
    "级": "級",
    "线": "線",
    "联": "聯",
    "轮": "輪",
    "边": "邊",
    "达": "達",
    "镜": "鏡",
    "险": "險",
    "从": "從",
    "后": "後",
    "为": "為爲",
    "刚": "剛",
    "复": "復複",
    "进": "進",
    "厂": "廠",
    "议": "議",
    "觉": "覺",
    "该": "該",
    "吗": "嗎",
    "还": "還",
    "国": "國",
    "拨": "撥",
    "设": "設",
    "统": "統",
}

_TRANSLATION = str.maketrans({
    variant: simplified
    for simplified, variants in SIMPLIFIED_TO_TRADITIONAL_VARIANTS.items()
    for variant in variants
})


def normalize_traditional(text: str) -> str:
    """Return a simplified copy for classification; do not alter ``text``."""
    return text.translate(_TRANSLATION)
